apiVersion: v1
kind: Service
metadata:
  name: spring-docker-minikube
spec:
  selector:
    app: spring-docker-minikube
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-docker-minikube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-docker-minikube
  template:
    metadata:
      labels:
        app: spring-docker-minikube
    spec:
      containers:
      - name: spring-docker-minikube
        image: spring-docker-minikube:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080